In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("my_file.csv")
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [18]:
# Data Inspection

print(df.shape)
df.info()

(20, 11)
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      str
 2   All Time Peak                     6 non-null      str
 3   Actual gross                      20 non-null     str
 4   Adjusted gross (in 2022 dollars)  20 non-null     str
 5   Artist                            20 non-null     str
 6   Tour title                        20 non-null     str
 7   Year(s)                           20 non-null     str
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     str
 10  Ref.                              20 non-null     str
dtypes: int64(2), str(9)
memory usage: 3.4 KB

In [19]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [20]:
# clean column name

df.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='str')

In [21]:
# clean the column name :

df.columns = df.columns.str.strip().str.upper().str.replace(" ","_")

In [22]:
df.head()

,RANK,PEAK,ALL_TIME_PEAK,ACTUAL GROSS,ADJUSTED GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [23]:
#Handle missing value names

df.columns

Index(['RANK', 'PEAK', 'ALL_TIME_PEAK', 'ACTUAL GROSS',
       'ADJUSTED GROSS_(IN_2022_DOLLARS)', 'ARTIST', 'TOUR_TITLE', 'YEAR(S)',
       'SHOWS', 'AVERAGE_GROSS', 'REF.'],
      dtype='str')

In [30]:
df.bfill(inplace=True)
df.ffill(inplace=True)

,RANK,PEAK,ALL_TIME_PEAK,ACTUAL GROSS,ADJUSTED GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],10[9],"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],14[17],"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,1[20],14[17],"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,1[20],14[17],"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,1[20],14[17],"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,1[20],14[17],"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,1[20],14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,1[20],14[17],"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],14[17],"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],14[17],"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,2[c],14[17],"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,2[c],14[17],"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,2[c],14[17],"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,2[c],14[17],"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,2[c],14[17],"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [31]:
df.isnull().sum()

RANK                                0
PEAK                                0
ALL_TIME_PEAK                       0
ACTUAL GROSS                        0
ADJUSTED GROSS_(IN_2022_DOLLARS)    0
ARTIST                              0
TOUR_TITLE                          0
YEAR(S)                             0
SHOWS                               0
AVERAGE_GROSS                       0
REF.                                0
dtype: int64

In [33]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [49]:
col_str=[]
all_col = df.columns
for i in all_col:
    print(i)
    if type(df.loc[0,i]) == type(" "):
        df[i] = df[i].str.strip().str.upper()

RANK
PEAK
ALL_TIME_PEAK
ACTUAL GROSS
ADJUSTED GROSS_(IN_2022_DOLLARS)
ARTIST
TOUR_TITLE
YEAR(S)
SHOWS
AVERAGE_GROSS
REF.

In [50]:
df.loc[0,"ARTIST"]

'TAYLOR SWIFT'

In [51]:
df.head()

,RANK,PEAK,ALL_TIME_PEAK,ACTUAL GROSS,ADJUSTED GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,1,1,2,"$780,000,000","$780,000,000",TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,"$2,546,795",[7]
4,5,2[4],10[9],"$345,675,146","$402,844,849",TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,"$6,522,173",[8]

In [52]:
df.reset_index(drop=True)

,RANK,PEAK,ALL_TIME_PEAK,ACTUAL GROSS,ADJUSTED GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,1,1,2,"$780,000,000","$780,000,000",TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,"$2,546,795",[7]
4,5,2[4],10[9],"$345,675,146","$402,844,849",TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",MADONNA,THE MDNA TOUR,2012,88,"$3,467,709",[9]
6,7,2[10],14[17],"$280,000,000","$381,932,682",CELINE DION,TAKING CHANCES WORLD TOUR,2008–2009,131,"$2,137,405",[11]
7,7,1[20],14[17],"$257,600,000","$257,600,000",PINK,SUMMER CARNIVAL †,2023–2024,41,"$6,282,927",[12]
8,9,1[20],14[17],"$256,084,556","$312,258,401",BEYONCÉ,THE FORMATION WORLD TOUR,2016,49,"$5,226,215",[13]
9,10,1[20],14[17],"$250,400,000","$309,141,878",TAYLOR SWIFT,THE 1989 WORLD TOUR,2015,85,"$2,945,882",[14]
10,11,1[20],14[17],"$229,100,000[B]","$283,202,896",BEYONCÉ,THE MRS. CARTER SHOW WORLD TOUR,2013–2014,132,"$1,735,606",[15][16]
11,12,1[20],14[17],"$227,400,000","$295,301,479",LADY GAGA,THE MONSTER BALL TOUR *,2009–2011,203,"$1,118,227",[18]
12,13,1[20],14[17],"$204,000,000","$251,856,802",KATY PERRY,PRISMATIC WORLD TOUR,2014–2015,151,"$1,350,993",[19]
13,14,1[20],14[17],"$200,000,000","$299,676,265",CHER,LIVING PROOF: THE FAREWELL TOUR ‡[21][A],2002–2005,325,"$615,385",[20]
14,15,2[C],14[17],"$194,000,000","$281,617,035",MADONNA,CONFESSIONS TOUR,2006,60,"$3,233,333",[5]
15,16,2[C],14[17],"$184,000,000","$227,452,347",PINK,THE TRUTH ABOUT LOVE TOUR,2013–2014,142,"$1,295,775",[22]
16,17,2[C],14[17],"$170,000,000","$213,568,571",LADY GAGA,BORN THIS WAY BALL,2012–2013,98,"$1,734,694",[D]
17,18,2[C],14[17],"$169,800,000","$207,046,755",MADONNA,REBEL HEART TOUR,2015–2016,82,"$2,070,732",[4]
18,19,2[C],14[17],"$167,700,000[E]","$204,486,106",ADELE,ADELE LIVE 2016,2016–2017,121,"$1,385,950",[25]
19,20,2[C],14[17],"$150,000,000","$185,423,109",TAYLOR SWIFT,THE RED TOUR,2013–2014,86,"$1,744,186",[26]

In [53]:
#Validate

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   RANK                              20 non-null     int64
 1   PEAK                              20 non-null     str
 2   ALL_TIME_PEAK                     20 non-null     str
 3   ACTUAL GROSS                      20 non-null     str
 4   ADJUSTED GROSS_(IN_2022_DOLLARS)  20 non-null     str
 5   ARTIST                            20 non-null     str
 6   TOUR_TITLE                        20 non-null     str
 7   YEAR(S)                           20 non-null     str
 8   SHOWS                             20 non-null     int64
 9   AVERAGE_GROSS                     20 non-null     str
 10  REF.                              20 non-null     str
dtypes: int64(2), str(9)
memory usage: 3.6 KB

In [54]:
df.describe()

            RANK       SHOWS
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [55]:
df.isnull().sum()

RANK                                0
PEAK                                0
ALL_TIME_PEAK                       0
ACTUAL GROSS                        0
ADJUSTED GROSS_(IN_2022_DOLLARS)    0
ARTIST                              0
TOUR_TITLE                          0
YEAR(S)                             0
SHOWS                               0
AVERAGE_GROSS                       0
REF.                                0
dtype: int64

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
import sqlite3

conn = sqlite3.connect("artist.db")

In [61]:
df = df.to_sql("artists",conn)

In [64]:
pd.read_sql_query("""SELECT * FROM artists""",conn)

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL GROSS,ADJUSTED GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,0,1,1,2,"$780,000,000","$780,000,000",TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,"$13,928,571",[1]
1,1,2,1,7[2],"$579,800,000","$579,800,000",BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,"$10,353,571",[3]
2,2,3,1[4],2[5],"$411,000,000","$560,622,615",MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,"$4,835,294",[6]
3,3,4,2[7],10[7],"$397,300,000","$454,751,555",PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,"$2,546,795",[7]
4,4,5,2[4],10[9],"$345,675,146","$402,844,849",TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,"$6,522,173",[8]
5,5,6,2[4],10[9],"$305,158,363","$388,978,496",MADONNA,THE MDNA TOUR,2012,88,"$3,467,709",[9]
6,6,7,2[10],14[17],"$280,000,000","$381,932,682",CELINE DION,TAKING CHANCES WORLD TOUR,2008–2009,131,"$2,137,405",[11]
7,7,7,1[20],14[17],"$257,600,000","$257,600,000",PINK,SUMMER CARNIVAL †,2023–2024,41,"$6,282,927",[12]
8,8,9,1[20],14[17],"$256,084,556","$312,258,401",BEYONCÉ,THE FORMATION WORLD TOUR,2016,49,"$5,226,215",[13]
9,9,10,1[20],14[17],"$250,400,000","$309,141,878",TAYLOR SWIFT,THE 1989 WORLD TOUR,2015,85,"$2,945,882",[14]
10,10,11,1[20],14[17],"$229,100,000[B]","$283,202,896",BEYONCÉ,THE MRS. CARTER SHOW WORLD TOUR,2013–2014,132,"$1,735,606",[15][16]
11,11,12,1[20],14[17],"$227,400,000","$295,301,479",LADY GAGA,THE MONSTER BALL TOUR *,2009–2011,203,"$1,118,227",[18]
12,12,13,1[20],14[17],"$204,000,000","$251,856,802",KATY PERRY,PRISMATIC WORLD TOUR,2014–2015,151,"$1,350,993",[19]
13,13,14,1[20],14[17],"$200,000,000","$299,676,265",CHER,LIVING PROOF: THE FAREWELL TOUR ‡[21][A],2002–2005,325,"$615,385",[20]
14,14,15,2[C],14[17],"$194,000,000","$281,617,035",MADONNA,CONFESSIONS TOUR,2006,60,"$3,233,333",[5]
15,15,16,2[C],14[17],"$184,000,000","$227,452,347",PINK,THE TRUTH ABOUT LOVE TOUR,2013–2014,142,"$1,295,775",[22]
16,16,17,2[C],14[17],"$170,000,000","$213,568,571",LADY GAGA,BORN THIS WAY BALL,2012–2013,98,"$1,734,694",[D]
17,17,18,2[C],14[17],"$169,800,000","$207,046,755",MADONNA,REBEL HEART TOUR,2015–2016,82,"$2,070,732",[4]
18,18,19,2[C],14[17],"$167,700,000[E]","$204,486,106",ADELE,ADELE LIVE 2016,2016–2017,121,"$1,385,950",[25]
19,19,20,2[C],14[17],"$150,000,000","$185,423,109",TAYLOR SWIFT,THE RED TOUR,2013–2014,86,"$1,744,186",[26]

In [66]:
pd.read_sql_query("""SELECT * FROM artists where SHOWS>150""",conn)

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL GROSS,ADJUSTED GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,3,4,2[7],10[7],"$397,300,000","$454,751,555",PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,"$2,546,795",[7]
1,11,12,1[20],14[17],"$227,400,000","$295,301,479",LADY GAGA,THE MONSTER BALL TOUR *,2009–2011,203,"$1,118,227",[18]
2,12,13,1[20],14[17],"$204,000,000","$251,856,802",KATY PERRY,PRISMATIC WORLD TOUR,2014–2015,151,"$1,350,993",[19]
3,13,14,1[20],14[17],"$200,000,000","$299,676,265",CHER,LIVING PROOF: THE FAREWELL TOUR ‡[21][A],2002–2005,325,"$615,385",[20]