In [17]:
import pandas as pd

In [27]:
df = pd.DataFrame({"Name":["Klein","Audrey","Alger"],"Age":[25,22,30]})

print(df)

print()

df["Financial Condition"]=["Low","High","Intermediate"]

print(df)

df.assign(alias=["Fool","Justice","Hanged Man"])

df.insert(1,"Country",3*["Leon Kingdom"])

df.assign(alias=["Fool","Justice","Hanged Man"])

     Name  Age
0   Klein   25
1  Audrey   22
2   Alger   30

     Name  Age Financial Condition
0   Klein   25                 Low
1  Audrey   22                High
2   Alger   30        Intermediate

     Name       Country  Age Financial Condition       alias
0   Klein  Leon Kingdom   25                 Low        Fool
1  Audrey  Leon Kingdom   22                High     Justice
2   Alger  Leon Kingdom   30        Intermediate  Hanged Man

In [ ]:
# 2.How to add an Index, row, or column to a Pandas DataFrame?

df["id"]=[100,101,102]

df.set_index("id",inplace=True)

       Name       Country  Age Financial Condition       alias
id
100   Klein  Leon Kingdom   25                 Low        Fool
101  Audrey  Leon Kingdom   22                High     Justice
102   Alger  Leon Kingdom   30        Intermediate  Hanged Man

In [36]:
df.loc[103] = ["Snurf", "Leon Kingdom", 0, "Low"]

df.assign(alias=["Fool","Justice","Hanged Man", "Mr. Word"])

       Name       Country  Age Financial Condition       alias
id
100   Klein  Leon Kingdom   25                 Low        Fool
101  Audrey  Leon Kingdom   22                High     Justice
102   Alger  Leon Kingdom   30        Intermediate  Hanged Man
103   Snurf  Leon Kingdom    0                 Low    Mr. Word

In [37]:
df.drop(103,inplace=True)

In [39]:
df.head()

       Name       Country  Age Financial Condition
id
100   Klein  Leon Kingdom   25                 Low
101  Audrey  Leon Kingdom   22                High
102   Alger  Leon Kingdom   30        Intermediate

In [41]:
df.drop('Age',axis=1)

       Name       Country Financial Condition
id
100   Klein  Leon Kingdom                 Low
101  Audrey  Leon Kingdom                High
102   Alger  Leon Kingdom        Intermediate

In [44]:
df.rename(columns={"Name":"Character"},inplace=True)

In [45]:
df.head()

    Character       Country  Age Financial Condition
id
100     Klein  Leon Kingdom   25                 Low
101    Audrey  Leon Kingdom   22                High
102     Alger  Leon Kingdom   30        Intermediate

In [47]:
df.rename(index={100:0},inplace=True)

In [48]:
df.head()

    Character       Country  Age Financial Condition
id
0       Klein  Leon Kingdom   25                 Low
101    Audrey  Leon Kingdom   22                High
102     Alger  Leon Kingdom   30        Intermediate

In [49]:
# 5.how to convert a numpy array to a dataframe of given shape?
import numpy as np
arr = np.array([1,2,3,4,5])

df = pd.DataFrame(arr)

print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [53]:
# 5.how to convert a numpy array to a dataframe of given shape?
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
df = pd.DataFrame(arr)

print(df)

   0  1  2
0  1  2  3
1  4  5  6

# 6. What is Pandas NumPy array?

- numerical python or numpy is python liabrary with lots of neumerical and scientific features

In [55]:
# 7.How can we convert DataFrame into an excel file?

df.to_excel("lom.xlsx")

In [61]:
# 8.How can we sort the DataFrame?

df.sort_values(0)

   0  1  2
0  1  2  3
1  4  5  6

In [63]:
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [50000, 40000, 60000, 45000]
})

df.groupby('Department')['Salary'].mean()

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

# 10. Define ReIndexing?

- reintializing index with new list of indices