In [2]:
import pandas as pd
import pathlib
import sqlite3

In [3]:
path = pathlib.Path(r"F:\Daily\Daily Problems\Day_17\Data Cleaning\artist.db")
print(path.exists())
print(path.is_file())
print(path.parent.exists())
conn = sqlite3.connect(path)
df = pd.read_sql_query("""SELECT * FROM artists""",conn)

True
True
True

In [4]:
df.head()

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL GROSS,ADJUSTED GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,0,1,1,2,"$780,000,000","$780,000,000",TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,"$13,928,571",[1]
1,1,2,1,7[2],"$579,800,000","$579,800,000",BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,"$10,353,571",[3]
2,2,3,1[4],2[5],"$411,000,000","$560,622,615",MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,"$4,835,294",[6]
3,3,4,2[7],10[7],"$397,300,000","$454,751,555",PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,"$2,546,795",[7]
4,4,5,2[4],10[9],"$345,675,146","$402,844,849",TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,"$6,522,173",[8]

In [5]:
df.columns = df.columns.str.strip().str.replace(r'\s+', '_', regex=True)

In [6]:
df.columns

Index(['index', 'RANK', 'PEAK', 'ALL_TIME_PEAK', 'ACTUAL GROSS',
       'ADJUSTED GROSS_(IN_2022_DOLLARS)', 'ARTIST', 'TOUR_TITLE', 'YEAR(S)',
       'SHOWS', 'AVERAGE_GROSS', 'REF.'],
      dtype='str')

In [7]:
df.columns = df.columns.str.replace('\xa0', '_', regex=False)

In [8]:
df.columns

Index(['index', 'RANK', 'PEAK', 'ALL_TIME_PEAK', 'ACTUAL_GROSS',
       'ADJUSTED_GROSS_(IN_2022_DOLLARS)', 'ARTIST', 'TOUR_TITLE', 'YEAR(S)',
       'SHOWS', 'AVERAGE_GROSS', 'REF.'],
      dtype='str')

In [9]:
df['ACTUAL_GROSS'] = df['ACTUAL_GROSS'].str.replace("$","")
df['ACTUAL_GROSS'] = df['ACTUAL_GROSS'].str.replace(",","")
df['ACTUAL_GROSS'] = df['ACTUAL_GROSS'].str.replace(r'\[.*?\]', '', regex=True)

In [10]:
df['ACTUAL_GROSS']

0     780000000
1     579800000
2     411000000
3     397300000
4     345675146
5     305158363
6     280000000
7     257600000
8     256084556
9     250400000
10    229100000
11    227400000
12    204000000
13    200000000
14    194000000
15    184000000
16    170000000
17    169800000
18    167700000
19    150000000
Name: ACTUAL_GROSS, dtype: str

In [11]:
df['ACTUAL_GROSS']=pd.to_numeric(df['ACTUAL_GROSS'])

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   index                             20 non-null     int64
 1   RANK                              20 non-null     int64
 2   PEAK                              20 non-null     str
 3   ALL_TIME_PEAK                     20 non-null     str
 4   ACTUAL_GROSS                      20 non-null     int64
 5   ADJUSTED_GROSS_(IN_2022_DOLLARS)  20 non-null     str
 6   ARTIST                            20 non-null     str
 7   TOUR_TITLE                        20 non-null     str
 8   YEAR(S)                           20 non-null     str
 9   SHOWS                             20 non-null     int64
 10  AVERAGE_GROSS                     20 non-null     str
 11  REF.                              20 non-null     str
dtypes: int64(4), str(8)
memory usage: 3.4 KB

In [13]:
df['ACTUAL_GROSS'].isnull().sum()

np.int64(0)

In [14]:
df.head()

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,0,1,1,2,780000000,"$780,000,000",TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,"$13,928,571",[1]
1,1,2,1,7[2],579800000,"$579,800,000",BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,"$10,353,571",[3]
2,2,3,1[4],2[5],411000000,"$560,622,615",MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,"$4,835,294",[6]
3,3,4,2[7],10[7],397300000,"$454,751,555",PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,"$2,546,795",[7]
4,4,5,2[4],10[9],345675146,"$402,844,849",TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,"$6,522,173",[8]

In [15]:
df['AVERAGE_GROSS'] = df['AVERAGE_GROSS'].str.replace("$","")
df['AVERAGE_GROSS'] = df['AVERAGE_GROSS'].str.replace(",","")
df['AVERAGE_GROSS'] = df['AVERAGE_GROSS'].str.replace(r'\[.*?\]', '', regex=True)

In [16]:
df['AVERAGE_GROSS']=pd.to_numeric(df['AVERAGE_GROSS'],errors='coerce')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   index                             20 non-null     int64
 1   RANK                              20 non-null     int64
 2   PEAK                              20 non-null     str
 3   ALL_TIME_PEAK                     20 non-null     str
 4   ACTUAL_GROSS                      20 non-null     int64
 5   ADJUSTED_GROSS_(IN_2022_DOLLARS)  20 non-null     str
 6   ARTIST                            20 non-null     str
 7   TOUR_TITLE                        20 non-null     str
 8   YEAR(S)                           20 non-null     str
 9   SHOWS                             20 non-null     int64
 10  AVERAGE_GROSS                     20 non-null     int64
 11  REF.                              20 non-null     str
dtypes: int64(5), str(7)
memory usage: 3.3 KB

In [18]:
df['AVERAGE_GROSS'].isnull().sum()

np.int64(0)

In [19]:
df['AVERAGE_GROSS'] = df['AVERAGE_GROSS'].fillna(
    df['AVERAGE_GROSS'].mean()
)

In [20]:
df['AVERAGE_GROSS'].dropna()

0     13928571
1     10353571
2      4835294
3      2546795
4      6522173
5      3467709
6      2137405
7      6282927
8      5226215
9      2945882
10     1735606
11     1118227
12     1350993
13      615385
14     3233333
15     1295775
16     1734694
17     2070732
18     1385950
19     1744186
Name: AVERAGE_GROSS, dtype: int64

In [21]:
df.isnull().sum()

index                               0
RANK                                0
PEAK                                0
ALL_TIME_PEAK                       0
ACTUAL_GROSS                        0
ADJUSTED_GROSS_(IN_2022_DOLLARS)    0
ARTIST                              0
TOUR_TITLE                          0
YEAR(S)                             0
SHOWS                               0
AVERAGE_GROSS                       0
REF.                                0
dtype: int64

In [22]:
df.head(10)

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,0,1,1,2,780000000,"$780,000,000",TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,13928571,[1]
1,1,2,1,7[2],579800000,"$579,800,000",BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,10353571,[3]
2,2,3,1[4],2[5],411000000,"$560,622,615",MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,4835294,[6]
3,3,4,2[7],10[7],397300000,"$454,751,555",PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,2546795,[7]
4,4,5,2[4],10[9],345675146,"$402,844,849",TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,6522173,[8]
5,5,6,2[4],10[9],305158363,"$388,978,496",MADONNA,THE MDNA TOUR,2012,88,3467709,[9]
6,6,7,2[10],14[17],280000000,"$381,932,682",CELINE DION,TAKING CHANCES WORLD TOUR,2008–2009,131,2137405,[11]
7,7,7,1[20],14[17],257600000,"$257,600,000",PINK,SUMMER CARNIVAL †,2023–2024,41,6282927,[12]
8,8,9,1[20],14[17],256084556,"$312,258,401",BEYONCÉ,THE FORMATION WORLD TOUR,2016,49,5226215,[13]
9,9,10,1[20],14[17],250400000,"$309,141,878",TAYLOR SWIFT,THE 1989 WORLD TOUR,2015,85,2945882,[14]

In [23]:
df.columns

Index(['index', 'RANK', 'PEAK', 'ALL_TIME_PEAK', 'ACTUAL_GROSS',
       'ADJUSTED_GROSS_(IN_2022_DOLLARS)', 'ARTIST', 'TOUR_TITLE', 'YEAR(S)',
       'SHOWS', 'AVERAGE_GROSS', 'REF.'],
      dtype='str')

In [24]:
df['ADJUSTED_GROSS_(IN_2022_DOLLARS)']=df['ADJUSTED_GROSS_(IN_2022_DOLLARS)'].str.replace('$','')

In [25]:
df['ADJUSTED_GROSS_(IN_2022_DOLLARS)']

0     780,000,000
1     579,800,000
2     560,622,615
3     454,751,555
4     402,844,849
5     388,978,496
6     381,932,682
7     257,600,000
8     312,258,401
9     309,141,878
10    283,202,896
11    295,301,479
12    251,856,802
13    299,676,265
14    281,617,035
15    227,452,347
16    213,568,571
17    207,046,755
18    204,486,106
19    185,423,109
Name: ADJUSTED_GROSS_(IN_2022_DOLLARS), dtype: str

In [26]:
df['ADJUSTED_GROSS_(IN_2022_DOLLARS)']=df['ADJUSTED_GROSS_(IN_2022_DOLLARS)'].str.replace(',','')

In [27]:
df['ADJUSTED_GROSS_(IN_2022_DOLLARS)'] =pd.to_numeric(df['ADJUSTED_GROSS_(IN_2022_DOLLARS)'])

In [28]:
df.shape

(20, 12)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   index                             20 non-null     int64
 1   RANK                              20 non-null     int64
 2   PEAK                              20 non-null     str
 3   ALL_TIME_PEAK                     20 non-null     str
 4   ACTUAL_GROSS                      20 non-null     int64
 5   ADJUSTED_GROSS_(IN_2022_DOLLARS)  20 non-null     int64
 6   ARTIST                            20 non-null     str
 7   TOUR_TITLE                        20 non-null     str
 8   YEAR(S)                           20 non-null     str
 9   SHOWS                             20 non-null     int64
 10  AVERAGE_GROSS                     20 non-null     int64
 11  REF.                              20 non-null     str
dtypes: int64(6), str(6)
memory usage: 3.0 KB

In [30]:
df.sort_index()

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS,REF.
0,0,1,1,2,780000000,780000000,TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,13928571,[1]
1,1,2,1,7[2],579800000,579800000,BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,10353571,[3]
2,2,3,1[4],2[5],411000000,560622615,MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,4835294,[6]
3,3,4,2[7],10[7],397300000,454751555,PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,2546795,[7]
4,4,5,2[4],10[9],345675146,402844849,TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,6522173,[8]
5,5,6,2[4],10[9],305158363,388978496,MADONNA,THE MDNA TOUR,2012,88,3467709,[9]
6,6,7,2[10],14[17],280000000,381932682,CELINE DION,TAKING CHANCES WORLD TOUR,2008–2009,131,2137405,[11]
7,7,7,1[20],14[17],257600000,257600000,PINK,SUMMER CARNIVAL †,2023–2024,41,6282927,[12]
8,8,9,1[20],14[17],256084556,312258401,BEYONCÉ,THE FORMATION WORLD TOUR,2016,49,5226215,[13]
9,9,10,1[20],14[17],250400000,309141878,TAYLOR SWIFT,THE 1989 WORLD TOUR,2015,85,2945882,[14]
10,10,11,1[20],14[17],229100000,283202896,BEYONCÉ,THE MRS. CARTER SHOW WORLD TOUR,2013–2014,132,1735606,[15][16]
11,11,12,1[20],14[17],227400000,295301479,LADY GAGA,THE MONSTER BALL TOUR *,2009–2011,203,1118227,[18]
12,12,13,1[20],14[17],204000000,251856802,KATY PERRY,PRISMATIC WORLD TOUR,2014–2015,151,1350993,[19]
13,13,14,1[20],14[17],200000000,299676265,CHER,LIVING PROOF: THE FAREWELL TOUR ‡[21][A],2002–2005,325,615385,[20]
14,14,15,2[C],14[17],194000000,281617035,MADONNA,CONFESSIONS TOUR,2006,60,3233333,[5]
15,15,16,2[C],14[17],184000000,227452347,PINK,THE TRUTH ABOUT LOVE TOUR,2013–2014,142,1295775,[22]
16,16,17,2[C],14[17],170000000,213568571,LADY GAGA,BORN THIS WAY BALL,2012–2013,98,1734694,[D]
17,17,18,2[C],14[17],169800000,207046755,MADONNA,REBEL HEART TOUR,2015–2016,82,2070732,[4]
18,18,19,2[C],14[17],167700000,204486106,ADELE,ADELE LIVE 2016,2016–2017,121,1385950,[25]
19,19,20,2[C],14[17],150000000,185423109,TAYLOR SWIFT,THE RED TOUR,2013–2014,86,1744186,[26]

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   index                             20 non-null     int64
 1   RANK                              20 non-null     int64
 2   PEAK                              20 non-null     str
 3   ALL_TIME_PEAK                     20 non-null     str
 4   ACTUAL_GROSS                      20 non-null     int64
 5   ADJUSTED_GROSS_(IN_2022_DOLLARS)  20 non-null     int64
 6   ARTIST                            20 non-null     str
 7   TOUR_TITLE                        20 non-null     str
 8   YEAR(S)                           20 non-null     str
 9   SHOWS                             20 non-null     int64
 10  AVERAGE_GROSS                     20 non-null     int64
 11  REF.                              20 non-null     str
dtypes: int64(6), str(6)
memory usage: 3.0 KB

In [32]:
df['PEAK'] = df['PEAK']

In [33]:
df['PEAK'] = df['PEAK'].str.replace(r'\[.*\]', '', regex=True)

In [34]:
df['PEAK'] = pd.to_numeric(df['PEAK'])

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   index                             20 non-null     int64
 1   RANK                              20 non-null     int64
 2   PEAK                              20 non-null     int64
 3   ALL_TIME_PEAK                     20 non-null     str
 4   ACTUAL_GROSS                      20 non-null     int64
 5   ADJUSTED_GROSS_(IN_2022_DOLLARS)  20 non-null     int64
 6   ARTIST                            20 non-null     str
 7   TOUR_TITLE                        20 non-null     str
 8   YEAR(S)                           20 non-null     str
 9   SHOWS                             20 non-null     int64
 10  AVERAGE_GROSS                     20 non-null     int64
 11  REF.                              20 non-null     str
dtypes: int64(7), str(5)
memory usage: 2.9 KB

In [36]:
df['ALL_TIME_PEAK'] = df['ALL_TIME_PEAK'].str.replace(r'\[.*\]','',regex=True)

In [37]:
df['ALL_TIME_PEAK'] = pd.to_numeric(df['ALL_TIME_PEAK'])

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   index                             20 non-null     int64
 1   RANK                              20 non-null     int64
 2   PEAK                              20 non-null     int64
 3   ALL_TIME_PEAK                     20 non-null     int64
 4   ACTUAL_GROSS                      20 non-null     int64
 5   ADJUSTED_GROSS_(IN_2022_DOLLARS)  20 non-null     int64
 6   ARTIST                            20 non-null     str
 7   TOUR_TITLE                        20 non-null     str
 8   YEAR(S)                           20 non-null     str
 9   SHOWS                             20 non-null     int64
 10  AVERAGE_GROSS                     20 non-null     int64
 11  REF.                              20 non-null     str
dtypes: int64(8), str(4)
memory usage: 2.8 KB

In [39]:
df.drop('REF.',axis=1,inplace=True)

In [40]:
df2= df.query('ALL_TIME_PEAK <= 10')

In [41]:
df.reset_index(drop=True)

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS
0,0,1,1,2,780000000,780000000,TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,13928571
1,1,2,1,7,579800000,579800000,BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,10353571
2,2,3,1,2,411000000,560622615,MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,4835294
3,3,4,2,10,397300000,454751555,PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,2546795
4,4,5,2,10,345675146,402844849,TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,6522173
5,5,6,2,10,305158363,388978496,MADONNA,THE MDNA TOUR,2012,88,3467709
6,6,7,2,14,280000000,381932682,CELINE DION,TAKING CHANCES WORLD TOUR,2008–2009,131,2137405
7,7,7,1,14,257600000,257600000,PINK,SUMMER CARNIVAL †,2023–2024,41,6282927
8,8,9,1,14,256084556,312258401,BEYONCÉ,THE FORMATION WORLD TOUR,2016,49,5226215
9,9,10,1,14,250400000,309141878,TAYLOR SWIFT,THE 1989 WORLD TOUR,2015,85,2945882
10,10,11,1,14,229100000,283202896,BEYONCÉ,THE MRS. CARTER SHOW WORLD TOUR,2013–2014,132,1735606
11,11,12,1,14,227400000,295301479,LADY GAGA,THE MONSTER BALL TOUR *,2009–2011,203,1118227
12,12,13,1,14,204000000,251856802,KATY PERRY,PRISMATIC WORLD TOUR,2014–2015,151,1350993
13,13,14,1,14,200000000,299676265,CHER,LIVING PROOF: THE FAREWELL TOUR ‡[21][A],2002–2005,325,615385
14,14,15,2,14,194000000,281617035,MADONNA,CONFESSIONS TOUR,2006,60,3233333
15,15,16,2,14,184000000,227452347,PINK,THE TRUTH ABOUT LOVE TOUR,2013–2014,142,1295775
16,16,17,2,14,170000000,213568571,LADY GAGA,BORN THIS WAY BALL,2012–2013,98,1734694
17,17,18,2,14,169800000,207046755,MADONNA,REBEL HEART TOUR,2015–2016,82,2070732
18,18,19,2,14,167700000,204486106,ADELE,ADELE LIVE 2016,2016–2017,121,1385950
19,19,20,2,14,150000000,185423109,TAYLOR SWIFT,THE RED TOUR,2013–2014,86,1744186

In [42]:
df2.reset_index(drop=True)

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS
0,0,1,1,2,780000000,780000000,TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,13928571
1,1,2,1,7,579800000,579800000,BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,10353571
2,2,3,1,2,411000000,560622615,MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,4835294
3,3,4,2,10,397300000,454751555,PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,2546795
4,4,5,2,10,345675146,402844849,TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,6522173
5,5,6,2,10,305158363,388978496,MADONNA,THE MDNA TOUR,2012,88,3467709

In [43]:
df2 = df2.sort_values(by=['AVERAGE_GROSS'],ascending=False)

In [44]:
df2

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS
0,0,1,1,2,780000000,780000000,TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,56,13928571
1,1,2,1,7,579800000,579800000,BEYONCÉ,RENAISSANCE WORLD TOUR,2023,56,10353571
4,4,5,2,10,345675146,402844849,TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,53,6522173
2,2,3,1,2,411000000,560622615,MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,85,4835294
5,5,6,2,10,305158363,388978496,MADONNA,THE MDNA TOUR,2012,88,3467709
3,3,4,2,10,397300000,454751555,PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,156,2546795

In [45]:
def shows(i):
        if i<=0:
            return 'ERROR!!!!!'
        elif i < 50:
            return 'Low'
        elif i>=50 and i<80:
            return 'Intermediate'
        elif i >=80 and i <100:
            return 'High'
        else:
            return ' Extraorinary'

In [46]:
df2['SHOWS']=df2['SHOWS'].apply(shows)

In [47]:
df2

,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS
0,0,1,1,2,780000000,780000000,TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,Intermediate,13928571
1,1,2,1,7,579800000,579800000,BEYONCÉ,RENAISSANCE WORLD TOUR,2023,Intermediate,10353571
4,4,5,2,10,345675146,402844849,TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,Intermediate,6522173
2,2,3,1,2,411000000,560622615,MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,High,4835294
5,5,6,2,10,305158363,388978496,MADONNA,THE MDNA TOUR,2012,High,3467709
3,3,4,2,10,397300000,454751555,PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,Extraorinary,2546795

In [48]:
df2.groupby('ARTIST')['SHOWS'].count()

ARTIST
BEYONCÉ         1
MADONNA         2
PINK            1
TAYLOR SWIFT    2
Name: SHOWS, dtype: int64

In [49]:
df2.groupby('ARTIST')['ACTUAL_GROSS'].sum()

ARTIST
BEYONCÉ          579800000
MADONNA          716158363
PINK             397300000
TAYLOR SWIFT    1125675146
Name: ACTUAL_GROSS, dtype: int64

In [50]:
df2.groupby('ARTIST')['ALL_TIME_PEAK'].mean().sort_values()

ARTIST
MADONNA          6.0
TAYLOR SWIFT     6.0
BEYONCÉ          7.0
PINK            10.0
Name: ALL_TIME_PEAK, dtype: float64

In [51]:
import sqlite3

conn = sqlite3.connect('updated_artists.db')

In [ ]:
# df2.to_sql('updated_artists_list',conn)

ValueError: Table 'updated_artists_list' already exists.

In [53]:
pd.read_sql_query("SELECT * FROM updated_artists_list",conn)

,level_0,index,RANK,PEAK,ALL_TIME_PEAK,ACTUAL_GROSS,ADJUSTED_GROSS_(IN_2022_DOLLARS),ARTIST,TOUR_TITLE,YEAR(S),SHOWS,AVERAGE_GROSS
0,0,0,1,1,2,780000000,780000000,TAYLOR SWIFT,THE ERAS TOUR †,2023–2024,Intermediate,13928571
1,1,1,2,1,7,579800000,579800000,BEYONCÉ,RENAISSANCE WORLD TOUR,2023,Intermediate,10353571
2,4,4,5,2,10,345675146,402844849,TAYLOR SWIFT,REPUTATION STADIUM TOUR,2018,Intermediate,6522173
3,2,2,3,1,2,411000000,560622615,MADONNA,STICKY & SWEET TOUR ‡[4][A],2008–2009,High,4835294
4,5,5,6,2,10,305158363,388978496,MADONNA,THE MDNA TOUR,2012,High,3467709
5,3,3,4,2,10,397300000,454751555,PINK,BEAUTIFUL TRAUMA WORLD TOUR,2018–2019,Extraorinary,2546795

In [56]:
df2.to_csv('transoformed.csv')