In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('my_file.csv')

In [6]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [7]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [8]:
# 2. Create a DataFrame from a NumPy array with custom column names.
import numpy as np

arr = np.array([1,2,3,4,5,6])

df =pd.DataFrame(arr)

In [9]:
df.columns = ['First']

In [10]:
df.columns

Index(['First'], dtype='object')

In [11]:
# 3. Select rows from a DataFrame based on multiple conditions.
df[df['First']>2]

   First
2      3
3      4
4      5
5      6

In [12]:
# 4. Select the first and last 7 rows of a Pandas DataFrame.
df

   First
0      1
1      2
2      3
3      4
4      5
5      6

In [13]:
# 4. Select the first and last 7 rows of a Pandas DataFrame.

df.head(6)

   First
0      1
1      2
2      3
3      4
4      5
5      6

In [17]:
# 5. Filter rows based on a condition in a specific column in a Pandas DataFrame.

def even_odd(x):
  if x % 2 == 0:
    return 'Even'
  else:
    return 'Odd'

df['First'] = df['First'].apply(even_odd)

In [18]:
df['First']

0     Odd
1    Even
2     Odd
3    Even
4     Odd
5    Even
Name: First, dtype: object

In [19]:
# 6. Create a new column in a Pandas DataFrame based on the result of a NumPy operation.
data = {
  'name' : ['jvm','python','sql'],
  'id' : ['a','b','c'],
  'size' : [100,2500,800]
}

In [20]:
df = pd.DataFrame(data)

In [21]:
df

     name id  size
0     jvm  a   100
1  python  b  2500
2     sql  c   800

In [22]:
df['size'] = df['size'] *2

In [23]:
df['size']

0     200
1    5000
2    1600
Name: size, dtype: int64

In [27]:
# 7. Merge two Pandas DataFrames based on a common column.
data1 = {
  'name' : ['jvm','python','sql'],
  'size' : [100,2500,800]
}

data1 = pd.DataFrame(data1)

data2 = {
  'name' : ['jvm','python','sql'],
  'id' : [1,2,3]
}

data2 = pd.DataFrame(data2)

In [29]:
merged_df = pd.merge(data1,data2,on='name',how='inner')

In [30]:
print(merged_df)

     name  size  id
0     jvm   100   1
1  python  2500   2
2     sql   800   3

In [31]:
# 8. Extract rows from a Pandas DataFrame where a specific column's values are in a given NumPy array.

idx = [0,1]

for i in idx:
  if i in merged_df.iloc[:,0]:
    print(merged_df.iloc[i,0])

jvm
python

In [46]:
# 9. Perform element-wise addition of a NumPy array and a Pandas DataFrame column.


data = {'Name': ['Teodosija', 'Sutton', 'Taneli', 'David', 'Ross'],
        'Age': [25, 30, 22, 35, 28],
        'Salary': [50000, 60000, 45000, 70000, 55000]}

add = np.array([10000,10000,10000,10000,10000])
df_add = pd.DataFrame(data)

df_add['update_Salary'] = df_add['Salary'] + add

In [47]:
df_add['update_Salary']

0    60000
1    70000
2    55000
3    80000
4    65000
Name: update_Salary, dtype: int64

In [35]:
# 10. Apply a NumPy function to a Pandas DataFrame column.

data = {'Name': ['Teodosija', 'Sutton', 'Taneli', 'David', 'Ross'],
        'Age': [25, 30, 22, 35, 28],
        'Salary': [50000, 60000, 45000, 70000, 55000]}


df_add = pd.DataFrame(data)

new_df = np.sqrt(df_add['Salary'])